### PR TITLE
Updated sys/ from Genesis core and wired up extra scanline level (75%)

### PR DESCRIPTION
**Pull request by rattboi**
This gets the coeff.txt loading, as well as another level of scanlines.

I'm not positive about the vip.qsys file changes. I can drop that from the PR if it's not appropriate.

### CODE REVIEW

**Comment by sorgelig** [comment]
So, you offer me copy my code from one my core to another?

I will do this myself when it will be about the time.

**Comment by coughlanio** [comment]
@sorgelig some constructive feedback would be helpful. If @rattboi making these changes allows you to do other work in your backlog, what's the harm? If you think there's issues in the code itself, having some PR comments would be very helpful for the PR author and other people contributing to the project.

**Comment by sorgelig** [comment]
1) I don't need PR which is bare copy from my own code. It doesn't save any time as most time consuming is testing and compiling.
2) New scaler features are in testing stage. Before propagate to other cores features must be set to avoid additional work. There is a discussion about the scaler on MiSTer forum.

I'm open to fixes and improvements as you may see from other PRs. But I see recently some strange PRs like removing couple unused wires or this bare copy of my own changes.

**Comment by rattboi** [comment]
That's fine. I am just learning how to contribute, and I did this as an exercise to make sure I understood the tools and interface a little bit. 

I thought I'd be saving time overall, and I didn't push a compiled RBF because I didn't think you'd accept that.

I'll try again with new features at some point. Sorry to waste your time.

**Comment by sorgelig** [comment]
No problem. As i've said, i'm open to improvements and fixing.

**Pull request closed without merging**
